name: moniepointflutterapp
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Flutter grids layout
  flutter_staggered_grid_view: ^0.7.0

  # Map
  google_maps_flutter: ^2.7.0

  # Map marker
  widget_to_marker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/files/
    - assets/images/
